import {
  Users,
  Code,
  GraduationCap,
  Scale,
  Building,
  HeartPulse,
  Briefcase,
  TrendingUp,
  BookOpen,
  ListTodo,
  ShieldCheck,
  Zap,
  LogIn,
  LayoutGrid,
  Link,
  Rocket,
  BrainCircuit,
  MessageSquare,
  FileText,
  CircleDot,
  Workflow,
  Sparkles,
  Star,
  ZapIcon,
  Users2,
  Building2,
  PlusCircle,
  GitMerge,
  Cloud,
  Server,
  LifeBuoy,
  GanttChartSquare,
  Newspaper,
  Mail,
  Github,
  Disc,
  Shield,
  File,
  Book,
  Code2,
  MessageCircle,
  Info,
} from "lucide-react"

export { testimonials } from './testimonials'
export { toolCategories } from './tool-categories'

export const useCases = [
  {
    audience: "CXOs & Executives",
    description: "Strategic dashboards, forecasting, and executive analytics.",
    tools: ["PredictMind", "InsightMind", "BenchMind", "+1"],
    icon: Briefcase,
    gradient: "from-blue-500 to-cyan-400",
  },
  {
    audience: "Product Managers",
    description: "Project tracking, user feedback, and growth analytics.",
    tools: ["ProjectMind", "FeedbackMind", "GrowthMind", "+1"],
    icon: ListTodo,
    gradient: "from-pink-500 to-orange-400",
  },
  {
    audience: "Developers",
    description: "Code generation, CI/CD, API management, and collaboration.",
    tools: ["CodeMind", "APIMind", "CloudMind", "+1"],
    icon: Code,
    gradient: "from-green-500 to-emerald-400",
  },
  {
    audience: "HR Teams",
    description: "Employee management, payroll, performance, and recruitment.",
    tools: ["PayrollMind", "RecruitMind", "PerformanceMind", "+1"],
    icon: Users,
    gradient: "from-purple-500 to-indigo-400",
  },
  {
    audience: "Sales Teams",
    description: "CRM, lead generation, pipeline management, and forecasting.",
    tools: ["CRMMind", "LeadMind", "SalesMind", "+1"],
    icon: TrendingUp,
    gradient: "from-emerald-500 to-teal-400",
  },
  {
    audience: "Legal Teams",
    description: "Case management, contracts, compliance, and documentation.",
    tools: ["LitigMind", "PolicyMind", "ComplianceMind", "+1"],
    icon: Scale,
    gradient: "from-indigo-500 to-violet-400",
  },
  {
    audience: "Students",
    description: "Note-taking, test preparation, scheduling, and collaboration.",
    tools: ["NoteMind", "TestMind", "CalMind", "+1"],
    icon: GraduationCap,
    gradient: "from-sky-500 to-blue-400",
  },
  {
    audience: "Real Estate",
    description: "Property management, listings, trading, and compliance.",
    tools: ["EstateMind", "PropertyMind", "TradeMind", "+1"],
    icon: Building,
    gradient: "from-rose-500 to-pink-400",
  },
  {
    audience: "Auditors",
    description: "Risk analysis, finance, compliance reviews, and risk management.",
    tools: ["AuditMind", "ComplianceMind", "RiskMind", "+1"],
    icon: ShieldCheck,
    gradient: "from-slate-500 to-gray-400",
  },
  {
    audience: "Educators",
    description: "Course planning, timetables, classroom management, and testing.",
    tools: ["EduMind", "ClassMind", "TestMind", "+1"],
    icon: BookOpen,
    gradient: "from-amber-500 to-yellow-400",
  },
  {
    audience: "Healthcare",
    description: "Patient management, reports, EHR, management, and growth insights.",
    tools: ["HealthMind", "MedicalMind", "PatientMind", "+1"],
    icon: HeartPulse,
    gradient: "from-red-500 to-orange-400",
  },
  {
    audience: "MSMEs",
    description: "Business tools, invoices, tax management, and growth insights.",
    tools: ["BizMind", "InvoiceMind", "TaxMind", "+1"],
    icon: Zap,
    gradient: "from-lime-500 to-green-400",
  },
]

export const howItWorksSteps = [
  {
    title: "Unified Login",
    description: "One account gives you access to all 70+ AI tools across every industry and role.",
    icon: LogIn,
  },
  {
    title: "Choose Your Tools",
    description: "Select from organized suites or browse individual tools that match your workflow needs.",
    icon: LayoutGrid,
  },
  {
    title: "Connect & Integrate",
    description: "Link your existing data sources and let AI understand your context for smarter automation.",
    icon: Link,
  },
  {
    title: "Get Work Done",
    description: "Experience seamless productivity with AI-powered tools that learn and adapt to your style.",
    icon: Rocket,
  },
]

export const aiFeatures = [
  {
    title: "GPT-4o Integration",
    description: "Powered by the latest OpenAI models for superior understanding and generation.",
    icon: BrainCircuit,
    gradient: "from-blue-500 to-purple-600",
  },
  {
    title: "Personal AI Assistant",
    description: "Your intelligent companion across all tools, learning your preferences.",
    icon: MessageSquare,
    gradient: "from-pink-500 to-fuchsia-500",
  },
  {
    title: "Auto-Fill & Suggestions",
    description: "Smart completion for forms, documents, and data entry tasks.",
    icon: Zap,
    gradient: "from-green-400 to-cyan-500",
  },
  {
    title: "Context-Aware Insights",
    description: "AI analyzes your work patterns to provide relevant recommendations.",
    icon: CircleDot,
    gradient: "from-orange-500 to-pink-500",
  },
  {
    title: "MindAgent Orchestration",
    description: "Multi-agent workflows that handle complex tasks automatically.",
    icon: Workflow,
    gradient: "from-cyan-400 to-emerald-400",
  },
  {
    title: "Intelligent Automation",
    description: "Smart workflows that adapt and improve with every interaction.",
    icon: Sparkles,
    gradient: "from-violet-500 to-fuchsia-500",
  },
]

export const pricingPlans = [
  {
    title: "Free",
    price: "$0",
    period: "/forever",
    description: "Perfect for students and individuals getting started.",
    icon: Star,
    features: [
      { text: "5 Core Tools Access", included: true },
      { text: "10 AI Queries/month", included: true },
      { text: "Basic Templates", included: true },
      { text: "Community Support", included: true },
      { text: "1 Workspace", included: true },
      { text: "Limited file uploads", included: true },
      { text: "Basic integrations only", included: false },
    ],
    cta: "Get Started Free",
    mostPopular: false,
  },
  {
    title: "Pro",
    price: "$29",
    period: "/per month",
    description: "For professionals and power-users.",
    icon: ZapIcon,
    features: [
      { text: "All 70+ Tools Access", included: true },
      { text: "Unlimited AI Queries", included: true },
      { text: "Advanced Templates", included: true },
      { text: "Priority Support", included: true },
      { text: "5 Workspaces", included: true },
      { text: "Mindagent Workflows", included: true },
      { text: "Custom Integrations", included: true },
      { text: "Advanced Analytics", included: true },
      { text: "API Access", included: true },
    ],
    cta: "Start Pro Trial",
    mostPopular: true,
  },
  {
    title: "Team",
    price: "$99",
    period: "/per month",
    description: "For small businesses and growing teams.",
    icon: Users2,
    features: [
      { text: "Everything in Pro", included: true },
      { text: "Up to 25 Team Members", included: true },
      { text: "Team Collaboration Tools", included: true },
      { text: "Admin Dashboard", included: true },
      { text: "Role-Based Permissions", included: true },
      { text: "Shared Workspaces", included: true },
      { text: "Team Analytics", included: true },
      { text: "SSO Integration", included: true },
      { text: "Custom Branding", included: true },
    ],
    cta: "Start Team Trial",
    mostPopular: false,
  },
  {
    title: "Enterprise",
    price: "Custom",
    period: "pricing",
    description: "For large organizations with custom needs.",
    icon: Building2,
    features: [
      { text: "Everything in Team", included: true },
      { text: "Unlimited Team Members", included: true },
      { text: "Custom Tool Development", included: true },
      { text: "Dedicated Support", included: true },
      { text: "On-premise Deployment", included: true },
      { text: "Custom AI Training", included: true },
      { text: "Advanced Security", included: true },
      { text: "SLA Guarantees", included: true },
      { text: "Migration Support", included: true },
    ],
    cta: "Contact Sales",
    mostPopular: false,
  },
]

export const specialPlans = [
  {
    title: "Education & Non-Profit",
    description: "Special pricing for educational institutions and non-profit organizations.",
    cta: "Learn More",
    badge: "50% Off",
  },
  {
    title: "Lifetime License",
    description: "One-time payment for lifetime access. Only 100 licenses available.",
    cta: "Learn More",
    badge: "Limited Time",
  },
]

export const footerLinks = {
  Product: [
    { name: "Features", href: "#", icon: Star },
    { name: "Pricing", href: "#", icon: PlusCircle },
    { name: "Documentation", href: "#", icon: Book },
    { name: "API Reference", href: "#", icon: Code2 },
    { name: "Changelog", href: "#", icon: GanttChartSquare },
    { name: "Roadmap", href: "#", icon: GitMerge },
  ],
  Company: [
    { name: "About Us", href: "#", icon: Info },
    { name: "Careers", href: "#", icon: Briefcase },
    { name: "Press Kit", href: "#", icon: Newspaper },
    { name: "Blog", href: "#", icon: FileText },
    { name: "Contact", href: "#", icon: Mail },
  ],
  Support: [
    { name: "Help Center", href: "#", icon: LifeBuoy },
    { name: "Community", href: "#", icon: Users },
    { name: "Discord", href: "#", icon: Disc },
    { name: "GitHub", href: "#", icon: Github },
    { name: "Status", href: "#", icon: Server },
  ],
  Legal: [
    { name: "Privacy Policy", href: "#", icon: Shield },
    { name: "Terms of Service", href: "#", icon: File },
    { name: "GDPR", href: "#", icon: Cloud },
    { name: "Cookie Policy", href: "#", icon: MessageCircle },
    { name: "Security", href: "#", icon: ShieldCheck },
  ],
}
